using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SistemaG9.Web.ViewModels
{
    public class RedeViewModel
    {
        public int Posicao_ID_0 { get; set; }
        public string Posicao_Apelido_0 { get; set; }
        public int Posicao_Status_0 { get; set; }

        // NIVEL 1
        public int Posicao_ID_1 { get; set; }
        public string Posicao_Apelido_1 { get; set; }
        public int Posicao_Status_1 { get; set; }
        public int Posicao_ID_2 { get; set; }
        public string Posicao_Apelido_2 { get; set; }
        public int Posicao_Status_2 { get; set; }
        public int Posicao_ID_3 { get; set; }
        public string Posicao_Apelido_3 { get; set; }
        public int Posicao_Status_3 { get; set; }

        //NIVEL 2
        public int Posicao_ID_4 { get; set; }
        public string Posicao_Apelido_4 { get; set; }
        public int Posicao_Status_4 { get; set; }
        public int Posicao_ID_5 { get; set; }
        public string Posicao_Apelido_5 { get; set; }
        public int Posicao_Status_5 { get; set; }
        public int Posicao_ID_6 { get; set; }
        public string Posicao_Apelido_6 { get; set; }
        public int Posicao_Status_6 { get; set; }
        public int Posicao_ID_7 { get; set; }
        public string Posicao_Apelido_7 { get; set; }
        public int Posicao_Status_7 { get; set; }
        public int Posicao_ID_8 { get; set; }
        public string Posicao_Apelido_8 { get; set; }
        public int Posicao_Status_8 { get; set; }
        public int Posicao_ID_9 { get; set; }
        public string Posicao_Apelido_9 { get; set; }
        public int Posicao_Status_9 { get; set; }
        public int Posicao_ID_10 { get; set; }
        public string Posicao_Apelido_10 { get; set; }
        public int Posicao_Status_10 { get; set; }
        public int Posicao_ID_11 { get; set; }
        public string Posicao_Apelido_11 { get; set; }
        public int Posicao_Status_11 { get; set; }
        public int Posicao_ID_12 { get; set; }
        public string Posicao_Apelido_12 { get; set; }
        public int Posicao_Status_12 { get; set; }

        // NIVEL 3
        public int Posicao_ID_13 { get; set; }
        public string Posicao_Apelido_13 { get; set; }
        public int Posicao_Status_13 { get; set; }
        public int Posicao_ID_14 { get; set; }
        public string Posicao_Apelido_14 { get; set; }
        public int Posicao_Status_14 { get; set; }
        public int Posicao_ID_15 { get; set; }
        public string Posicao_Apelido_15 { get; set; }
        public int Posicao_Status_15 { get; set; }
        public int Posicao_ID_16 { get; set; }
        public string Posicao_Apelido_16 { get; set; }
        public int Posicao_Status_16 { get; set; }
        public int Posicao_ID_17 { get; set; }
        public string Posicao_Apelido_17 { get; set; }
        public int Posicao_Status_17 { get; set; }
        public int Posicao_ID_18 { get; set; }
        public string Posicao_Apelido_18 { get; set; }
        public int Posicao_Status_18 { get; set; }
        public int Posicao_ID_19 { get; set; }
        public string Posicao_Apelido_19 { get; set; }
        public int Posicao_Status_19 { get; set; }
        public int Posicao_ID_20 { get; set; }
        public string Posicao_Apelido_20 { get; set; }
        public int Posicao_Status_20 { get; set; }
        public int Posicao_ID_21 { get; set; }
        public string Posicao_Apelido_21 { get; set; }
        public int Posicao_Status_21 { get; set; }

        public int Posicao_ID_22 { get; set; }
        public string Posicao_Apelido_22 { get; set; }
        public int Posicao_Status_22 { get; set; }
        public int Posicao_ID_23 { get; set; }
        public string Posicao_Apelido_23 { get; set; }
        public int Posicao_Status_23 { get; set; }
        public int Posicao_ID_24 { get; set; }
        public string Posicao_Apelido_24 { get; set; }
        public int Posicao_Status_24 { get; set; }
        public int Posicao_ID_25 { get; set; }
        public string Posicao_Apelido_25 { get; set; }
        public int Posicao_Status_25 { get; set; }
        public int Posicao_ID_26 { get; set; }
        public string Posicao_Apelido_26 { get; set; }
        public int Posicao_Status_26 { get; set; }
        public int Posicao_ID_27 { get; set; }
        public string Posicao_Apelido_27 { get; set; }
        public int Posicao_Status_27 { get; set; }
        public int Posicao_ID_28 { get; set; }
        public string Posicao_Apelido_28 { get; set; }
        public int Posicao_Status_28 { get; set; }
        public int Posicao_ID_29 { get; set; }
        public string Posicao_Apelido_29 { get; set; }
        public int Posicao_Status_29 { get; set; }
        public int Posicao_ID_30 { get; set; }
        public string Posicao_Apelido_30 { get; set; }
        public int Posicao_Status_30 { get; set; }
        public int Posicao_ID_31 { get; set; }
        public string Posicao_Apelido_31 { get; set; }
        public int Posicao_Status_31 { get; set; }
        public int Posicao_ID_32 { get; set; }
        public string Posicao_Apelido_32 { get; set; }
        public int Posicao_Status_32 { get; set; }
        public int Posicao_ID_33 { get; set; }
        public string Posicao_Apelido_33 { get; set; }
        public int Posicao_Status_33 { get; set; }
        public int Posicao_ID_34 { get; set; }
        public string Posicao_Apelido_34 { get; set; }
        public int Posicao_Status_34 { get; set; }
        public int Posicao_ID_35 { get; set; }
        public string Posicao_Apelido_35 { get; set; }
        public int Posicao_Status_35 { get; set; }
        public int Posicao_ID_36 { get; set; }
        public string Posicao_Apelido_36 { get; set; }
        public int Posicao_Status_36 { get; set; }
        public int Posicao_ID_37 { get; set; }
        public string Posicao_Apelido_37 { get; set; }
        public int Posicao_Status_37 { get; set; }
        public int Posicao_ID_38 { get; set; }
        public string Posicao_Apelido_38 { get; set; }
        public int Posicao_Status_38 { get; set; }
        public int Posicao_ID_39 { get; set; }
        public string Posicao_Apelido_39 { get; set; }
        public int Posicao_Status_39 { get; set; }
        public int Posicao_ID_40 { get; set; }
        public string Posicao_Apelido_40 { get; set; }
        public int Posicao_Status_40 { get; set; }

        //NIVEL 4
        public int Posicao_ID_41 { get; set; }
        public string Posicao_Apelido_41 { get; set; }
        public int Posicao_Status_41 { get; set; }
        public int Posicao_ID_42 { get; set; }
        public string Posicao_Apelido_42 { get; set; }
        public int Posicao_Status_42 { get; set; }
        public int Posicao_ID_43 { get; set; }
        public string Posicao_Apelido_43 { get; set; }
        public int Posicao_Status_43 { get; set; }
        public int Posicao_ID_44 { get; set; }
        public string Posicao_Apelido_44 { get; set; }
        public int Posicao_Status_44 { get; set; }
        public int Posicao_ID_45 { get; set; }
        public string Posicao_Apelido_45 { get; set; }
        public int Posicao_Status_45 { get; set; }
        public int Posicao_ID_46 { get; set; }
        public string Posicao_Apelido_46 { get; set; }
        public int Posicao_Status_46 { get; set; }
        public int Posicao_ID_47 { get; set; }
        public string Posicao_Apelido_47 { get; set; }
        public int Posicao_Status_47 { get; set; }
        public int Posicao_ID_48 { get; set; }
        public string Posicao_Apelido_48 { get; set; }
        public int Posicao_Status_48 { get; set; }
        public int Posicao_ID_49 { get; set; }
        public string Posicao_Apelido_49 { get; set; }
        public int Posicao_Status_49 { get; set; }
        public int Posicao_ID_50 { get; set; }
        public string Posicao_Apelido_50 { get; set; }
        public int Posicao_Status_50 { get; set; }
        public int Posicao_ID_51 { get; set; }
        public string Posicao_Apelido_51 { get; set; }
        public int Posicao_Status_51 { get; set; }
        public int Posicao_ID_52 { get; set; }
        public string Posicao_Apelido_52 { get; set; }
        public int Posicao_Status_52 { get; set; }
        public int Posicao_ID_53 { get; set; }
        public string Posicao_Apelido_53 { get; set; }
        public int Posicao_Status_53 { get; set; }
        public int Posicao_ID_54 { get; set; }
        public string Posicao_Apelido_54 { get; set; }
        public int Posicao_Status_54 { get; set; }
        public int Posicao_ID_55 { get; set; }
        public string Posicao_Apelido_55 { get; set; }
        public int Posicao_Status_55 { get; set; }
        public int Posicao_ID_56 { get; set; }
        public string Posicao_Apelido_56 { get; set; }
        public int Posicao_Status_56 { get; set; }
        public int Posicao_ID_57 { get; set; }
        public string Posicao_Apelido_57 { get; set; }
        public int Posicao_Status_57 { get; set; }
        public int Posicao_ID_58 { get; set; }
        public string Posicao_Apelido_58 { get; set; }
        public int Posicao_Status_58 { get; set; }
        public int Posicao_ID_59 { get; set; }
        public string Posicao_Apelido_59 { get; set; }
        public int Posicao_Status_59 { get; set; }
        public int Posicao_ID_60 { get; set; }
        public string Posicao_Apelido_60 { get; set; }
        public int Posicao_Status_60 { get; set; }
        public int Posicao_ID_61 { get; set; }
        public string Posicao_Apelido_61 { get; set; }
        public int Posicao_Status_61 { get; set; }
        public int Posicao_ID_62 { get; set; }
        public string Posicao_Apelido_62 { get; set; }
        public int Posicao_Status_62 { get; set; }
        public int Posicao_ID_63 { get; set; }
        public string Posicao_Apelido_63 { get; set; }
        public int Posicao_Status_63 { get; set; }
        public int Posicao_ID_64 { get; set; }
        public string Posicao_Apelido_64 { get; set; }
        public int Posicao_Status_64 { get; set; }
        public int Posicao_ID_65 { get; set; }
        public string Posicao_Apelido_65 { get; set; }
        public int Posicao_Status_65 { get; set; }
        public int Posicao_ID_66 { get; set; }
        public string Posicao_Apelido_66 { get; set; }
        public int Posicao_Status_66 { get; set; }
        public int Posicao_ID_67 { get; set; }
        public string Posicao_Apelido_67 { get; set; }
        public int Posicao_Status_67 { get; set; }
        public int Posicao_ID_68 { get; set; }
        public string Posicao_Apelido_68 { get; set; }
        public int Posicao_Status_68 { get; set; }
        public int Posicao_ID_69 { get; set; }
        public string Posicao_Apelido_69 { get; set; }
        public int Posicao_Status_69 { get; set; }
        public int Posicao_ID_70 { get; set; }
        public string Posicao_Apelido_70 { get; set; }
        public int Posicao_Status_70 { get; set; }
        public int Posicao_ID_71 { get; set; }
        public string Posicao_Apelido_71 { get; set; }
        public int Posicao_Status_71 { get; set; }
        public int Posicao_ID_72 { get; set; }
        public string Posicao_Apelido_72 { get; set; }
        public int Posicao_Status_72 { get; set; }
        public int Posicao_ID_73 { get; set; }
        public string Posicao_Apelido_73 { get; set; }
        public int Posicao_Status_73 { get; set; }
        public int Posicao_ID_74 { get; set; }
        public string Posicao_Apelido_74 { get; set; }
        public int Posicao_Status_74 { get; set; }
        public int Posicao_ID_75 { get; set; }
        public string Posicao_Apelido_75 { get; set; }
        public int Posicao_Status_75 { get; set; }
        public int Posicao_ID_76 { get; set; }
        public string Posicao_Apelido_76 { get; set; }
        public int Posicao_Status_76 { get; set; }
        public int Posicao_ID_77 { get; set; }
        public string Posicao_Apelido_77 { get; set; }
        public int Posicao_Status_77 { get; set; }
        public int Posicao_ID_78 { get; set; }
        public string Posicao_Apelido_78 { get; set; }
        public int Posicao_Status_78 { get; set; }
        public int Posicao_ID_79 { get; set; }
        public string Posicao_Apelido_79 { get; set; }
        public int Posicao_Status_79 { get; set; }
        public int Posicao_ID_80 { get; set; }
        public string Posicao_Apelido_80 { get; set; }
        public int Posicao_Status_80 { get; set; }
        public int Posicao_ID_81 { get; set; }
        public string Posicao_Apelido_81 { get; set; }
        public int Posicao_Status_81 { get; set; }
        public int Posicao_ID_82 { get; set; }
        public string Posicao_Apelido_82 { get; set; }
        public int Posicao_Status_82 { get; set; }
        public int Posicao_ID_83 { get; set; }
        public string Posicao_Apelido_83 { get; set; }
        public int Posicao_Status_83 { get; set; }
        public int Posicao_ID_84 { get; set; }
        public string Posicao_Apelido_84 { get; set; }
        public int Posicao_Status_84 { get; set; }
        public int Posicao_ID_85 { get; set; }
        public string Posicao_Apelido_85 { get; set; }
        public int Posicao_Status_85 { get; set; }
        public int Posicao_ID_86 { get; set; }
        public string Posicao_Apelido_86 { get; set; }
        public int Posicao_Status_86 { get; set; }
        public int Posicao_ID_87 { get; set; }
        public string Posicao_Apelido_87 { get; set; }
        public int Posicao_Status_87 { get; set; }
        public int Posicao_ID_88 { get; set; }
        public string Posicao_Apelido_88 { get; set; }
        public int Posicao_Status_88 { get; set; }
        public int Posicao_ID_89 { get; set; }
        public string Posicao_Apelido_89 { get; set; }
        public int Posicao_Status_89 { get; set; }
        public int Posicao_ID_90 { get; set; }
        public string Posicao_Apelido_90 { get; set; }
        public int Posicao_Status_90 { get; set; }
        public int Posicao_ID_91 { get; set; }
        public string Posicao_Apelido_91 { get; set; }
        public int Posicao_Status_91 { get; set; }
        public int Posicao_ID_92 { get; set; }
        public string Posicao_Apelido_92 { get; set; }
        public int Posicao_Status_92 { get; set; }
        public int Posicao_ID_93 { get; set; }
        public string Posicao_Apelido_93 { get; set; }
        public int Posicao_Status_93 { get; set; }
        public int Posicao_ID_94 { get; set; }
        public string Posicao_Apelido_94 { get; set; }
        public int Posicao_Status_94 { get; set; }
        public int Posicao_ID_95 { get; set; }
        public string Posicao_Apelido_95 { get; set; }
        public int Posicao_Status_95 { get; set; }
        public int Posicao_ID_96 { get; set; }
        public string Posicao_Apelido_96 { get; set; }
        public int Posicao_Status_96 { get; set; }
        public int Posicao_ID_97 { get; set; }
        public string Posicao_Apelido_97 { get; set; }
        public int Posicao_Status_97 { get; set; }
        public int Posicao_ID_98 { get; set; }
        public string Posicao_Apelido_98 { get; set; }
        public int Posicao_Status_98 { get; set; }
        public int Posicao_ID_99 { get; set; }
        public string Posicao_Apelido_99 { get; set; }
        public int Posicao_Status_99 { get; set; }
        public int Posicao_ID_100 { get; set; }
        public string Posicao_Apelido_100 { get; set; }
        public int Posicao_Status_100 { get; set; }
        public int Posicao_ID_101 { get; set; }
        public string Posicao_Apelido_101 { get; set; }
        public int Posicao_Status_101 { get; set; }
        public int Posicao_ID_102 { get; set; }
        public string Posicao_Apelido_102 { get; set; }
        public int Posicao_Status_102 { get; set; }
        public int Posicao_ID_103 { get; set; }
        public string Posicao_Apelido_103 { get; set; }
        public int Posicao_Status_103 { get; set; }
        public int Posicao_ID_104 { get; set; }
        public string Posicao_Apelido_104 { get; set; }
        public int Posicao_Status_104 { get; set; }
        public int Posicao_ID_105 { get; set; }
        public string Posicao_Apelido_105 { get; set; }
        public int Posicao_Status_105 { get; set; }
        public int Posicao_ID_106 { get; set; }
        public string Posicao_Apelido_106 { get; set; }
        public int Posicao_Status_106 { get; set; }
        public int Posicao_ID_107 { get; set; }
        public string Posicao_Apelido_107 { get; set; }
        public int Posicao_Status_107 { get; set; }
        public int Posicao_ID_108 { get; set; }
        public string Posicao_Apelido_108 { get; set; }
        public int Posicao_Status_108 { get; set; }
        public int Posicao_ID_109 { get; set; }
        public string Posicao_Apelido_109 { get; set; }
        public int Posicao_Status_109 { get; set; }
        public int Posicao_ID_110 { get; set; }
        public string Posicao_Apelido_110 { get; set; }
        public int Posicao_Status_110 { get; set; }
        public int Posicao_ID_111 { get; set; }
        public string Posicao_Apelido_111 { get; set; }
        public int Posicao_Status_111 { get; set; }
        public int Posicao_ID_112 { get; set; }
        public string Posicao_Apelido_112 { get; set; }
        public int Posicao_Status_112 { get; set; }
        public int Posicao_ID_113 { get; set; }
        public string Posicao_Apelido_113 { get; set; }
        public int Posicao_Status_113 { get; set; }
        public int Posicao_ID_114 { get; set; }
        public string Posicao_Apelido_114 { get; set; }
        public int Posicao_Status_114 { get; set; }
        public int Posicao_ID_115 { get; set; }
        public string Posicao_Apelido_115 { get; set; }
        public int Posicao_Status_115 { get; set; }
        public int Posicao_ID_116 { get; set; }
        public string Posicao_Apelido_116 { get; set; }
        public int Posicao_Status_116 { get; set; }
        public int Posicao_ID_117 { get; set; }
        public string Posicao_Apelido_117 { get; set; }
        public int Posicao_Status_117 { get; set; }
        public int Posicao_ID_118 { get; set; }
        public string Posicao_Apelido_118 { get; set; }
        public int Posicao_Status_118 { get; set; }
        public int Posicao_ID_119 { get; set; }
        public string Posicao_Apelido_119 { get; set; }
        public int Posicao_Status_119 { get; set; }
        public int Posicao_ID_120 { get; set; }
        public string Posicao_Apelido_120 { get; set; }
        public int Posicao_Status_120 { get; set; }
        public int Posicao_ID_121 { get; set; }
        public string Posicao_Apelido_121 { get; set; }
        public int Posicao_Status_121 { get; set; }
    }
}